LIST

In [1]:
numbers = [20, 21, 45, 56, 34]
numbers

[20, 21, 45, 56, 34]

In [2]:
type(numbers)

list

In [4]:
letters = ["a", "b", "c", "d"]
type(letters)

list

In [5]:
combined = numbers + letters
combined

[20, 21, 45, 56, 34, 'a', 'b', 'c', 'd']

In [6]:
type(combined)

list

In [8]:
matrix = [[0,1],[2,3]]
type(matrix)

list

In [9]:
zeros = [0]*5
zeros

[0, 0, 0, 0, 0]

In [10]:
num = list(range(20))
num

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [11]:
char = list("Hello world")
char

['H', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']

In [12]:
letters

['a', 'b', 'c', 'd']

In [13]:
letters[0]

'a'

In [14]:
letters[0:4]

['a', 'b', 'c', 'd']

In [15]:
letters[::-1]

['d', 'c', 'b', 'a']

In [16]:
letters[0] = "z"
letters

['z', 'b', 'c', 'd']

In [17]:
letters[1] = 23
letters

['z', 23, 'c', 'd']

In [18]:
letters.append("e")
letters

['z', 23, 'c', 'd', 'e']

In [19]:
letters.pop()

'e'

In [20]:
letters

['z', 23, 'c', 'd']

In [21]:
letters.pop(2)
letters

['z', 23, 'd']

In [22]:
del letters[0:2]
letters

['d']

In [25]:
numbers

[56, 45, 34, 21, 20]

In [27]:
numbers.sort()
numbers

[20, 21, 34, 45, 56]

In [28]:
numbers

[20, 21, 34, 45, 56]

In [30]:
numbers.sort(reverse=True)
numbers

[56, 45, 34, 21, 20]

Tuples

In [31]:
point = (1,2,3,4)
type(point)

tuple

In [32]:
point1 = 1,2,3,4

In [33]:
point1

(1, 2, 3, 4)

In [35]:
final = point + point1
final

(1, 2, 3, 4, 1, 2, 3, 4)

In [36]:
mix = (1,2,"d","e")
type(mix)

tuple

In [37]:
point1[1]

2

In [38]:
point1[0] = 9 #Tuples Can't be changed

TypeError: 'tuple' object does not support item assignment

Dictionaries

In [39]:
dict1 = {"x":1, "y":2}
dict1

{'x': 1, 'y': 2}

In [40]:
type(dict1)

dict

In [41]:
dict2 = dict(x=1, y=2)

In [42]:
dict2

{'x': 1, 'y': 2}

In [43]:
dict1 = {"x":[1,2,3,4], "y":2}

In [44]:
dict1

{'x': [1, 2, 3, 4], 'y': 2}

In [45]:
dict1["x"]

[1, 2, 3, 4]

In [46]:
dict1["z"] = [10,20,30]

In [47]:
dict1

{'x': [1, 2, 3, 4], 'y': 2, 'z': [10, 20, 30]}

In [48]:
dict1.keys()

dict_keys(['x', 'y', 'z'])

In [49]:
dict1.values()

dict_values([[1, 2, 3, 4], 2, [10, 20, 30]])

Exception Handling


In [50]:
num1 = [2,3]
num1[3]

IndexError: list index out of range

In [54]:
try:
  num1 = [2,3]
  print(num1[3])
except IndexError:
  print("Not working")

Not working


In [55]:
age = int(input("Age:"))

Age:qww


ValueError: invalid literal for int() with base 10: 'qww'

In [56]:
try:
  age = int(input("Age:"))
except ValueError:
  print("You didn't enter the valid age")

Age:qww
You didn't enter the valid age


In [57]:
try:
  age = int(input("Age:"))
except ValueError as ex:
  print("You didn't enter the valid age")
  print(ex)

Age:qww
You didn't enter the valid age
invalid literal for int() with base 10: 'qww'


Functions:

1: Pre-defined
2: User defined


In [58]:
def greet_user():
  print('Hi there..')
  print('Welcome aboard')


print("start")
greet_user()
print("stop")

start
Hi there..
Welcome aboard
stop


In [59]:
def greet_user(first_name, last_name): #Parameters
  print(f'Hi {first_name} {last_name}')
  print('Welcome aboard')


print("start")
greet_user("Rahul", "Singh")   #Arguments
print("stop")

start
Hi Rahul Singh
Welcome aboard
stop


In [60]:
import math
math.factorial(4)

24

In [61]:
import time
for i in range(0,20):
  print(i)
  time.sleep(1)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [62]:
def greet(name):
  print(f'Hi {name}')


print(greet('Rahul'))

Hi Rahul
None


In [63]:
def greet(name):
  print(f'Hi {name}')
  return "..."


print(greet('Rahul'))

Hi Rahul
...


Numpy

In [64]:
import numpy as np
n = np.array([2,3,4,5,6])
n

array([2, 3, 4, 5, 6])

Attributes

In [65]:
n.ndim

1

In [66]:
n.shape

(5,)

In [67]:
n.size

5

In [68]:
n2 = np.array([[2,3,4,5,6],[1,23,41,16,21]])
n2

array([[ 2,  3,  4,  5,  6],
       [ 1, 23, 41, 16, 21]])

In [69]:
n2.ndim

2

In [70]:
n2.shape

(2, 5)

In [71]:
n2.size

10

In [72]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [73]:
n2

array([[ 2,  3,  4,  5,  6],
       [ 1, 23, 41, 16, 21]])

In [74]:
n2[0,0]

2

In [75]:
n2[0,1]

3

In [76]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [77]:
a.ndim

3

In [78]:
a.shape

(1, 3, 3)

In [79]:
a[0,0,0]

1

In [80]:
a[0,1,0]

4

In [81]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [82]:
a*b

array([ 4, 10, 18])

In [83]:
k = np.arange(0,18)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [84]:
k.shape

(18,)

In [85]:
k.reshape(3, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [86]:
k = k.reshape(2,9)

In [87]:
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

slicing

In [88]:
k[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

In [89]:
k[0:2,4:7]

array([[ 4,  5,  6],
       [13, 14, 15]])

In [90]:
k =k.reshape(3, 6)
k

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [91]:
a = np.arange(0,10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])